[build]
    functions="dist"
    publish = "dist"
    node_version = "20.11.0"

[functions]
  external_node_modules = ["express", "ejs"]
  node_bundler = "esbuild"

[[redirects]]
    force=true
    to="/.netlify/functions/index"
    from="/*"
    status=200

[[headers]]
  for = "/api/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"